# Twist Mux Configuration for Aurora
twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic:   "/nav_vel"
        timeout: 0.5
        priority: 10
      teleop_joy:
        topic:   "/joy_vel"
        timeout: 0.5
        priority: 50
      teleop_direct:
        topic:   "/teleop_vel"
        timeout: 0.5
        priority: 60
      emergency:
        topic:   "/stop_vel"
        timeout: 0.5
        priority: 100
